version: "3.8"  
services: 
  mysql:
          image: mysql:latest 
          container_name: mysql 
          networks:
                  - mynetwork 
          volumes: 
                  - /home/huuquan/mysql-server:/etc/mysql/conf.d 
          restart: always
          environment:
                  MYSQL_ROOT_PASSWORD: Luonghuuquan1!
                  MYSQL_USER: quanluong
                  MYSQL_DATABASE: wordpress 
                  MYSQL_PASSWORD: Luonghuuquan1! 
  wordpress_1:
          depends_on: 
                  - mysql 
          image: wordpress:php8.0-apache
          container_name: wp1 
          networks:
                  - mynetwork
          restart: always 
          ports:
                  - "8000:80"
          environment: 
                  WORDPRESS_DB_HOST: mysql:3306
                  WORDPRESS_DB_USER: quanluong
                  WORDPRESS_DB_NAME: wordpress
                  WORDPRESS_DB_PASSWORD: Luonghuuquan1!
  wordpressi_2: 
         depends_on:
                  - mysql 
         image: wordpress:php8.0-apache
         container_name: wp2 
         restart: always 
         networks: 
                  - mynetwork
         ports: 
                  - "9000:80"
         environment:
                  WORDPRESS_DB_HOST: mysql:3306
                  WORDPRESS_DB_USER: quanluong
                  WORDPRESS_DB_NAME: wordpress
                  WORDPRESS_DB_PASSWORD: Luonghuuquan1!
networks: 
       mynetwork:
               driver: bridge 
